/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16. scene.glb 
Author: ErickJohnP (https://sketchfab.com/ErickJohnP)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/headphones-7769b32522db412ea89fa0067d9bf36d
Title: Headphones
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import scene from "./scene.glb";
import { useFrame } from "@react-three/fiber";

export function Model(props) {
  const ref = useRef();
  const { nodes, materials } = useGLTF(scene);

  useFrame(() => ref.current && (ref.current.rotation.y += 0.005));

  return (
    <group
      {...props}
      dispose={null}
      ref={ref}
      position={props.position || [3, -0.5, 0]}
      scale={props.scale || 0.0058}
    >
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Circle_Plastic_0.geometry}
          material={materials.Plastic}
        />
        <mesh
          geometry={nodes.Circle_BlueLight_0.geometry}
          material={materials.BlueLight}
        />
        <mesh
          geometry={nodes.Circle_OrangeLight_0.geometry}
          material={materials.OrangeLight}
        />
      </group>
      <group
        position={[277.439, -164.932, 0]}
        rotation={[-Math.PI / 2, -1.13, 0]}
        scale={[99.883, 80.399, 54.019]}
      >
        <mesh
          geometry={nodes.Circle001_Plastic_0.geometry}
          material={materials.Plastic}
        />
        <mesh
          geometry={nodes.Circle001_Lather_0.geometry}
          material={materials.Lather}
        />
      </group>
      <mesh
        geometry={nodes.Grid_Plastic_0.geometry}
        material={materials.Plastic}
        position={[173.761, -115.009, 0]}
        rotation={[-Math.PI / 2, -1.13, 0]}
        scale={109.944}
      />
    </group>
  );
}

useGLTF.preload("./scene.glb");
